version: "3.9"

services:
  database:
    image: mysql:9.2.0-oracle
    working_dir: /database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_NAME: ${MYSQL_NAME}
    volumes:
      - databaseVolume:/var/lib/mysql
      - ./init_scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  frontend:
    image: blog-project-front:latest
    build: ./frontend
    ports:
      - "3000:80"

  backend:
    image: blog-project-back:latest
    build: ./backend
    working_dir: /backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_URL: ${MYSQL_URL}
    ports: 
      - "8080:8080"
    depends_on:
      - database
  
volumes:
  databaseVolume: